services:
  remnawave-db:
    image: postgres:17.6
    container_name: 'remnawave-db'
    hostname: remnawave-db
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=UTC
    ports:
      - '127.0.0.1:6767:5432'
    volumes:
      - remnawave-db-data:/var/lib/postgresql/data
    networks:
      - remnawave-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      interval: 3s
      timeout: 10s
      retries: 3

  remnawave:
    image: remnawave/backend:2
    container_name: 'remnawave'
    hostname: remnawave
    restart: always
    # command: [ "pm2-runtime", "start", "ecosystem.config.js", "--env", "development" ]
    ports:
      - '3000'
    env_file:
      - .env
    networks:
      - remnawave-network
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:${METRICS_PORT:-3001}/health']
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    depends_on:
      remnawave-db:
        condition: service_healthy
      remnawave-redis:
        condition: service_healthy

  remnawave-redis:
    image: valkey/valkey:8.1-alpine
    container_name: remnawave-redis
    hostname: remnawave-redis
    restart: always
    networks:
      - remnawave-network
    volumes:
      - remnawave-redis-data:/data
    healthcheck:
      test: ['CMD', 'valkey-cli', 'ping']
      interval: 3s
      timeout: 10s
      retries: 3

  ts-traefik:
    image: tailscale/tailscale:latest
    container_name: test-ts-traefik
    hostname: ${TS_NAME}
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_SOCKET=/var/run/tailscale/tailscaled.sock
      --advertise-tags=test
    volumes:
      - ./tailscale/data:/var/lib/tailscale:rw
      - ./tailscale:/var/run/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    networks:
      - remnawave-network
    depends_on:
      remnawave:
        condition: service_healthy

    restart: unless-stopped

  traefik:
    image: traefik:latest
    container_name: test-traefik
    network_mode: service:ts-traefik
    depends_on:
      - ts-traefik
    volumes:
      - ./traefik.yml:/traefik.yml:ro
      - ./traefik/logs:/logs:rw
      # Access to Docker socket for provider, discovery.
      - /var/run/docker.sock:/var/run/docker.sock
      # Access to Tailscale files for cert generation.
      - ./tailscale/data:/var/lib/tailscale:rw
      # Access to Tailscale socket for cert generation.
      - ./tailscale:/var/run/tailscale
    labels:
      - traefik.http.routers.traefik_https.entrypoints=https
      - traefik.http.routers.traefik_https.service=api@internal
      - traefik.http.routers.traefik_https.tls=true
      - traefik.http.routers.traefik_https.tls.certresolver=myresolver
      - traefik.http.routers.traefik_https.tls.domains[0].main=${TS_NAME}.${TS_TAILNET}
      - traefik.http.services.${TS_NAME}.loadbalancer.server.port=443


networks:
  remnawave-network:
    name: remnawave-network
    driver: bridge
    external: false

volumes:
  remnawave-db-data:
    driver: local
    external: false
    name: remnawave-db-data
  remnawave-redis-data:
    driver: local
    external: false
    name: remnawave-redis-data
