services:

  cloudflare-ddns:
    image: favonia/cloudflare-ddns:latest
    restart: always
    read_only: true
    cap_drop: [all]
    security_opt: [no-new-privileges:true]
    environment:
      - CLOUDFLARE_API_TOKEN=${CF_TOKEN}
      - DOMAINS=${DOMAIN}

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    volumes:
      # Mount the certs volume to store certificates
      - ./cert_data:/etc/letsencrypt
      - ./renew_entrypoint.sh:/entrypoint.sh
    env_file:
      - .env
    ports:
      - "80:80"
    environment:
      - DOMAIN=${DOMAIN}
    entrypoint: /entrypoint.sh
    depends_on:
      - cloudflare-ddns
    healthcheck:
      test: ["CMD-SHELL", "test -f /etc/letsencrypt/live/certs/privkey.pem || exit 1"]
      interval: 1s
      timeout: 5s
      retries: 3
      start_period: 600s

  remnawave-nginx:
    image: nginx:1.28
    container_name: remnawave-nginx
    hostname: remnawave-nginx
    restart: always
    env_file:
      - .env
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./cert_data/live/certs/fullchain.pem:/etc/nginx/ssl/certs/fullchain.pem:ro
      - ./cert_data/live/certs/privkey.pem:/etc/nginx/ssl/certs/privkey.pem:ro
      - /dev/shm:/dev/shm:rw
      - ./site:/var/www/html:ro
    command: sh -c 'rm -f /dev/shm/nginx.sock && nginx -g "daemon off;"'
    logging:
      driver: 'json-file'
      options:
        max-size: '30m'
        max-file: '5'
    depends_on:
      certbot:
        condition: service_healthy


  ts:
    image: tailscale/tailscale:latest
    container_name: ts
    hostname: ${DOMAIN}
    env_file:
      - .env
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_SOCKET=/var/run/tailscale/tailscaled.sock
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
    volumes:
      - ./tailscale/data:/var/lib/tailscale:rw
      - ./tailscale:/var/run/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    ports:
      # Map port 443 from the host to this container, making it public
      - "443:443"
    restart: unless-stopped

  remnanode:
    image: remnawave/node:latest
    container_name: remnanode
    restart: always
    network_mode: service:ts
    depends_on:
      - ts
    env_file:
      - .env
    volumes:
      - /dev/shm:/dev/shm:rw
    logging:
      driver: 'json-file'
      options:
        max-size: '30m'
        max-file: '5'
